%YAML 1.2
---
# [MkDocs 配置文件](https://www.mkdocs.org/user-guide/configuration/)

#
# [Project information](https://www.mkdocs.org/user-guide/configuration/#project-information)
#

site_name: zhengrr's docs
site_url: https://afoolsbag.github.io/
repo_url: https://github.com/afoolsbag/afoolsbag.github.io/
edit_uri: "tree/master/docs"
site_description: 一份为 zhengrr 定制化的技术备忘。
site_author: zhengrr
copyright: CC0-1.0

#
# [Documentation layout](https://www.mkdocs.org/user-guide/configuration/#documentation-layout)
#

nav:
  - index.md
  - 音乐:
    - music/index.md
  - 开发运维:
      - dev-ops/index.md
      - dev-ops/crypt.md
      - dev-ops/int-cen.md
      - dev-ops/markdown.md
      - dev-ops/uml.md
      - dev-ops/git.md
      - dev-ops/gitflow.md
      - dev-ops/gitlab.md
      - dev-ops/jenkins.md
      - dev-ops/sqlpad.md
      - 壳层:
          - Xshell: dev-ops/shell/xshell.md
      - 虚拟化:
          - Docker: dev-ops/virt/docker.md
          - VMware: dev-ops/virt/vmware.md
          - VirtualBox: dev-ops/virt/virtualbox.md
  - 应用:
      - apps/index.md
      - 文本:
          - apps/text/emacs.md
          - Vim: apps/text/vim.md
      - 图像:
          - apps/image/gimp.md
      - 音频:
          - apps/audio/audacity.md
      - 视频:
          - apps/video/ffmpeg.md
          - apps/video/vlc.md
      - 三维计算机图形:
          - apps/3dcg/blender.md
      - apps/gpt-2.md
      - apps/yolo.md
  - 中间件:
      - mws/index.md
      - SSH: mws/ssh.md
      - mws/ceph.md
      - mws/ftp.md
      - mws/kafka.md
      - mws/mysql.md
      - mws/nginx.md
      - mws/nginx-rtmp-module.md
      - mws/postgresql.md
      - mws/zookeeper.md
  - 操作系统:
      - oss/index.md
      - oss/naming.md
      - 壳层:
          - oss/shs/index.md
      - 兼容:
          - oss/xps/index.md
      - Kali:
          - oss/kali/index.md
          - APT: oss/ubuntu/apt.md
          - oss/kali/dirbuster.md
          - oss/kali/nmap.md
          - oss/kali/skipfish.md
      - Ubuntu:
          - oss/ubuntu/index.md
          - APT: oss/ubuntu/apt.md
          - deb: oss/ubuntu/deb.md
      - CentOS:
          - oss/centos/index.md
          - oss/centos/dnf.md
      - NixOS:
          - oss/nixos/index.md
          - Nix: oss/nixos/nix.md
      - Arch:
          - oss/arch/index.md
          - oss/arch/pacman.md
      - GNU/Linux:
          - oss/linux/index.md
          - Nix: oss/nixos/nix.md
          - Coreutils:
              - oss/linux/coreutils/index.md
          - iproute2:
              - oss/linux/iproute2/index.md
          - net-tools:
              - oss/linux/net-tools/index.md
          - procps:
              - oss/linux/procps/index.md
          - systemd:
              - oss/linux/systemd/index.md
          - util-linux:
              - oss/linux/util-linux/index.md
          - oss/linux/cockpit.md
          - fish: oss/linux/fish.md
          - oss/linux/man-db.md
          - oss/linux/netfilter.md
          - oss/linux/networking.md
          - oss/linux/tar.md
          - oss/linux/tldr.md
          - oss/linux/top.md
          - oss/linux/users.md
      - Windows:
          - oss/windows/index.md
          - oss/windows/chocolatey.md
          - oss/windows/scoop.md
          - oss/windows/cheat-engine.md
          - oss/windows/cmder.md
          - oss/windows/cygwin.md
          - oss/windows/terminal.md
          - oss/windows/wsl.md
      - 引导:
          - oss/booting/index.md
          - GRUB: oss/booting/grub.md
  - 虚拟化:
      - virts/index.md
  - 硬件:
      - hws/index.md

#
# [Build directories](https://www.mkdocs.org/user-guide/configuration/#build-directories)
#

theme:
  # [使用 Material 主题](https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration)
  name: material

  # [颜色](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: 切换到日常模式

  # [语言](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/)
  language: zh

  # [图标](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/)
  logo: assets/images/book-open-page-variant.png
  favicon: assets/images/book-open-page-variant.png
  icon:
    repo: fontawesome/brands/github

  # 功能
  features:
    # [导航](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/)
#   - navigation.expand
    - navigation.indexes
    - navigation.instant
#   - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate

    # [搜索](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/)
    - search.suggest
    - search.highlight
    - search.share

    # [页眉](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/)
    - header.autohide

    # [内容选项卡](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/)
    - content.tabs.link

extra_css:
  # [abcjs](https://abcjs.net/)
  - https://unpkg.com/abcjs@6.1.6/abcjs-audio.css
  - assets/stylesheets/abcjs.css

extra_javascript:
  # [MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # [Sortable tables](https://squidfunk.github.io/mkdocs-material/reference/data-tables/?h=table+sort#sortable-tables)
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.date.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.dotsep.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.filesize.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.monthname.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.number.min.js
  - assets/javascripts/tablesort.js
  # [abcjs](https://abcjs.net/)
  - https://unpkg.com/abcjs@6.1.6/dist/abcjs-basic-min.js
  - assets/javascripts/abcjs.js
  # [Plotly](https://plotly.com/javascript/)
  - https://unpkg.com/plotly.js@2.16.3/dist/plotly-basic.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/afoolsbag
      name: afoolsbag on GitHub

#
# [Formatting options](https://www.mkdocs.org/user-guide/configuration/#formatting-options)
#

markdown_extensions:
  #-----------------------------------# [Python-Markdown 官方扩展包](https://python-markdown.github.io/extensions/)
# - markdown.extensions.extra         # Extra
  - markdown.extensions.abbr          # ├[Abbreviations](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#abbreviations)
  - markdown.extensions.attr_list     # ├[Attribute Lists](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists)
  - markdown.extensions.def_list      # ├[Definition Lists](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#definition-lists)
# - markdown.extensions.fenced_code   # ├[Fenced Code Blocks](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#fenced-code-blocks)
  - markdown.extensions.footnotes     # ├[Footnotes](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes)
  - markdown.extensions.md_in_html    # ├[Markdown in HTML](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html)
  - markdown.extensions.tables        # └[Tables](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables)
  - markdown.extensions.admonition    # [Admonition](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition)
# - markdown.extensions.codehilite    # [CodeHilite](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#codehilite)
# - markdown.extensions.legacy_attrs  # Legacy Attributes
# - markdown.extensions.legacy_em     # Legacy Emphasis
  - markdown.extensions.meta          # [Meta-Data](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#metadata)
# - markdown.extensions.nl2br         # New Line to Break
  - markdown.extensions.sane_lists    # Sane Lists
  - markdown.extensions.smarty        # SmartyPants
  - markdown.extensions.toc:          # [Table of Contents](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents)
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
# - markdown.extensions.wikilinks     # WikiLinks

  #-----------------------------------# [PyMdown 第三方扩展包](https://facelessuser.github.io/pymdown-extensions/)
# - pymdownx.extra                    # Extra
  - pymdownx.betterem                 # ├BetterEm
# - markdown.extensions.abbr          # ├Abbreviations
# - markdown.extensions.attr_list     # ├Attribute Lists
# - markdown.extensions.def_list      # ├Definition Lists
  - pymdownx.superfences:             # ├SuperFences
      custom_fences:                  #  [Custom Fences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#custom-fences)
        - name: mermaid               #   [Diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/)
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: abc                   #   []
          class: abctext
          format: !!python/name:pymdownx.superfences.fence_code_format
# - markdown.extensions.footnotes     # ├Footnotes
# - markdown.extensions.md_in_html    # ├Markdown in HTML
# - markdown.extensions.tables        # └Tables
  - pymdownx.arithmatex:              # Arithmatex
      generic: true                   #   [MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)
# - pymdownx.b64                      # B64
  - pymdownx.caret                    # Caret
  - pymdownx.critic                   # Critic
  - pymdownx.details                  # Details
  - pymdownx.emoji:                   # Emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# - pymdownx.escapeall                # EscapeAll
  - pymdownx.highlight                # Highlight
  - pymdownx.inlinehilite             # InlineHilite
  - pymdownx.keys                     # Keys
  - pymdownx.magiclink                # MagicLink
  - pymdownx.mark                     # Mark
# - pymdownx.pathconverter            # PathConverter
# - pymdownx.progressbar              # ProgressBar
  - pymdownx.saneheaders              # SaneHeaders
  - pymdownx.smartsymbols             # SmartSymbols
  - pymdownx.snippets                 # Snippets
  - pymdownx.striphtml                # StripHTML
  - pymdownx.tabbed:                  # Tabbed
      alternate_style: true
  - pymdownx.tasklist                 # Tasklist
#     custom_checkbox: true
  - pymdownx.tilde                    # Tilde

plugins:
  - git-revision-date-localized
  - minify:
      minify_html: true
  - search
