# MkDocs 配置文件
# https://www.mkdocs.org/user-guide/configuration/

# Project information
# https://www.mkdocs.org/user-guide/configuration/#project-information
site_name: zhengrr's docs
site_url: https://afoolsbag.github.io/
repo_url: https://github.com/afoolsbag/afoolsbag.github.io/
edit_uri: 'tree/mkdocs/docs'
site_description: 一份为 zhengrr 定制化的技术备忘。
site_author: zhengrr
copyright: CC0-1.0

# Documentation layout
# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
nav:
    - 码代码:
        - CC/CC.md
        - CC/Vim.md
        - CC/Emacs.md
        - CC/UML.md
    - 多媒体:
        - MM/MM.md
        - MM/Audacity.md
        - MM/Blender.md
        - MM/FFmpeg.md
        - MM/GIMP.md
        - MM/GPT-2.md
        - MM/VLC.md
    - 中间件:
        - MW/Ceph.md
        - MW/FTP.md
        - MW/Kafka.md
        - MW/MySQL.md
        - MW/NGINX.md
        - MW/nginx-rtmp-module.md
        - MW/PostgreSQL.md
        - MW/ZooKeeper.md
    - 操作系统:
        - OS/OS.md
        - Windows:
            - OS/Windows/Windows.md
            - OS/Windows/Scoop & Chocolatey.md
            - OS/Windows/Cmder.md
            - OS/Windows/Cheat Engine.md
            - OS/Windows/WSL.md
        - GNU/Linux:
            - OS/Linux/Linux.md
            - OS/Linux/fish.md
            - OS/Linux/netfilter.md
            - OS/Linux/networking.md
            - OS/Linux/tar.md
            - OS/Linux/top.md
            - OS/Linux/users.md
        - Arch:
            - OS/Arch/Arch.md
            - OS/Arch/pacman.md
        - CentOS:
            - OS/CentOS/CentOS.md
            - OS/CentOS/dnf.md
        - Ubuntu:
            - OS/Ubuntu/Ubuntu.md
            - OS/Ubuntu/apt.md
        - Tails:
            - OS/Tails/Tails.md
        - Kali:
            - OS/Kali/Kali.md
            - OS/Kali/DirBuster.md
            - OS/Kali/Nmap.md
            - OS/Kali/skipfish.md
        - OS/VMware.md
        - OS/VirtualBox.md
        - OS/Xshell.md
    - 开发运维:
        - DevOps/DevOps.md
        - DevOps/Git.md
        - DevOps/GitFlow.md
        - DevOps/GitLab.md
        - DevOps/Jenkins.md
        - DevOps/Docker.md
        - DevOps/Ansible.md

# Build directories
# https://www.mkdocs.org/user-guide/configuration/#build-directories
theme:
    name: material
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    favicon: assets/images/book-open-page-variant.png
    features:
        - header.autohide
        - navigation.expand
        - navigation.instant
        - navigation.tabs
        - toc.autohide
    icon:
        logo: material/book-open-page-variant
        repo: fontawesome/brands/github
    language: zh
    palette:
        scheme: preference
    # https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md
extra_javascript:
    - assets/javascripts/highlight.pack.js

# Preview controls
# https://www.mkdocs.org/user-guide/configuration/#preview-controls

# Formatting options
# https://www.mkdocs.org/user-guide/configuration/#formatting-options
markdown_extensions:
    - markdown.extensions.sane_lists
    - markdown.extensions.toc:
        permalink: true
        slugify: !!python/name:pymdownx.slugs.uslugify
    - pymdownx.keys
    - pymdownx.superfences
plugins:
    - git-revision-date-localized
    - minify:
        minify_html: true
    - search
