# MkDocs 配置文件
# https://www.mkdocs.org/user-guide/configuration/

# Project information
# https://www.mkdocs.org/user-guide/configuration/#project-information
site_name: zhengrr's docs
site_url: https://afoolsbag.github.io/
repo_url: https://github.com/afoolsbag/afoolsbag.github.io/
edit_uri: ''
site_description: 一份为 zhengrr 定制化的技术备忘。
site_author: zhengrr
copyright: CC0-1.0

# Documentation layout
# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
nav:
    - 码代码:
        - CC/CC.md
        - CC/Vim.md
        - CC/Emacs.md
        - CC/UML.md
    - 音视频:
        - AV/AV.md
        - AV/FFmpeg.md
        - AV/VLC.md
    - 中间件:
        - MW/Ceph.md
        - MW/FTP.md
        - MW/Kafka.md
        - MW/MySQL.md
        - MW/NGINX.md
        - MW/nginx-rtmp-module.md
        - MW/ZooKeeper.md
    - 操作系统:
        - OS/OS.md
        - Windows:
            - OS/Windows/Windows.md
            - OS/Windows/Scoop & Chocolatey.md
            - OS/Windows/Cmder.md
            - OS/Windows/Cheat Engine.md
            - OS/Windows/WSL.md
        - GNU/Linux:
            - OS/Linux/Linux.md
            - OS/Linux/Arch.md
            - OS/Linux/apt.md
            - OS/Linux/yum.md
            - OS/Linux/pacman.md
            - OS/Linux/fish.md
            - OS/Linux/netfilter.md
            - OS/Linux/networking.md
            - OS/Linux/tar.md
            - OS/Linux/top.md
            - OS/Linux/users.md
        - Kali:
            - OS/Kali/DirBuster.md
            - OS/Kali/Nmap.md
            - OS/Kali/skipfish.md
        - OS/VMware.md
        - OS/VirtualBox.md
        - OS/Xshell.md
    - 开发运维:
        - DevOps/DevOps.md
        - DevOps/Git.md
        - DevOps/GitLab.md
        - DevOps/Jenkins.md
        - DevOps/Docker.md
        - DevOps/Ansible.md

# Build directories
# https://www.mkdocs.org/user-guide/configuration/#build-directories

theme:
    name: mkdocs
    hljs_languages:
        - bash
        - cmd
        - cmder
        - nginx
        - zsh
    prev_next_buttons_location: none
    navigation_depth: 4

# Preview controls
# https://www.mkdocs.org/user-guide/configuration/#preview-controls

# Formatting options
# https://www.mkdocs.org/user-guide/configuration/#formatting-options
