# MkDocs 配置文件
# https://www.mkdocs.org/user-guide/configuration/

# Project information
# https://www.mkdocs.org/user-guide/configuration/#project-information
site_name: zhengrr's docs
site_url: https://afoolsbag.github.io/
repo_url: https://github.com/afoolsbag/afoolsbag.github.io/
edit_uri: ''
site_description: 一份为 zhengrr 定制化的技术备忘。
site_author: zhengrr
copyright: CC0-1.0

# Documentation layout
# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
nav:
    - 码代码:
        - CC/CC.md
        - CC/Vim.md
        - CC/Emacs.md
        - CC/StarUML.md
    - 音视频:
        - AV/AV.md
        - AV/FFmpeg.md
        - AV/VLC.md
    - 中间件:
        - MW/MySQL.md
        - MW/NGINX.md
        - MW/nginx-rtmp-module.md
    - 操作系统:
        - OS/OS.md
        - Windows:
            - OS/Windows/Windows.md
            - OS/Windows/arp.md
            - OS/Windows/choco.md
            - OS/Windows/ipconfig.md
            - OS/Windows/PE.md
            - OS/Windows/scoop.md
        - GNU/Linux:
            - OS/Linux/Linux.md
            - OS/Linux/bootstrap.md
            - OS/Linux/ELF.md
            - OS/Linux/fish.md
            - OS/Linux/grep.md
            - OS/Linux/link aggregation.md
            - OS/Linux/netfilter.md
            - OS/Linux/tar.md
            - OS/Linux/top.md
            - OS/Linux/users.md
        - Debian:
            - OS/Debian/apt.md
            - OS/Debian/apt-toolchain.md
        - Arch:
            - OS/Arch/Arch.md
            - OS/Arch/pacman.md
            - OS/Arch/pacman-devel.md
        - CentOS:
            - OS/CentOS/CentOS.md
            - OS/CentOS/yum.md
            - OS/CentOS/yum-devtoolset.md
        - Kali:
            - OS/Kali/Kali.md
            - OS/Kali/DirBuster.md
            - OS/Kali/Nmap.md
            - OS/Kali/skipfish.md
        - OS/VMware.md
        - OS/VirtualBox.md
        - OS/Xshell.md
    - 开发运维:
        - DevOps/DevOps.md
        - DevOps/Git.md
        - DevOps/GitLab.md
        - DevOps/Jenkins.md
        - DevOps/Docker.md
        - DevOps/Ansible.md

# Build directories
# https://www.mkdocs.org/user-guide/configuration/#build-directories

# Preview controls
# https://www.mkdocs.org/user-guide/configuration/#preview-controls

# Formatting options
# https://www.mkdocs.org/user-guide/configuration/#formatting-options
